# Generated by Django 6.0.2 on 2026-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0002_alter_edit_thumbnail_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='edits.profile'),
        ),
    ]
