# Generated by Django 6.0.2 on 2026-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0003_profile_bio_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='edit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='edits', to='edits.tag'),
        ),
    ]
