# Generated by Django 6.0.2 on 2026-02-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0004_tag_edit_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
